/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SafePotInterface extends Interface {
    getFunction(nameOrSignature: "CREATION_FEE" | "contribute" | "createGroup" | "getGroup" | "groups" | "hasRugged" | "installmentAmount" | "inviteCodeToGroupId" | "inviterOf" | "joinGroup" | "joinPrivateGroup" | "memberContributions" | "nextGroupId" | "pendingInstallments" | "slashInviter" | "slashPublicMember" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContributionMade" | "GroupCreated" | "JoinedGroup" | "PotDistributed"): EventFragment;

    encodeFunctionData(functionFragment: 'CREATION_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createGroup', values: [string, BigNumberish, BigNumberish, string, boolean, string]): string;
encodeFunctionData(functionFragment: 'getGroup', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'groups', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasRugged', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'installmentAmount', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'inviteCodeToGroupId', values: [string]): string;
encodeFunctionData(functionFragment: 'inviterOf', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'joinGroup', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'joinPrivateGroup', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'memberContributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextGroupId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingInstallments', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'slashInviter', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'slashPublicMember', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CREATION_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createGroup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGroup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'groups', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRugged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'installmentAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inviteCodeToGroupId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inviterOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinGroup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinPrivateGroup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'memberContributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextGroupId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingInstallments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashInviter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashPublicMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace ContributionMadeEvent {
      export type InputTuple = [groupId: BigNumberish, member: AddressLike, amount: BigNumberish];
      export type OutputTuple = [groupId: bigint, member: string, amount: bigint];
      export interface OutputObject {groupId: bigint, member: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GroupCreatedEvent {
      export type InputTuple = [groupId: BigNumberish, name: string, creator: AddressLike];
      export type OutputTuple = [groupId: bigint, name: string, creator: string];
      export interface OutputObject {groupId: bigint, name: string, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JoinedGroupEvent {
      export type InputTuple = [groupId: BigNumberish, member: AddressLike];
      export type OutputTuple = [groupId: bigint, member: string];
      export interface OutputObject {groupId: bigint, member: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PotDistributedEvent {
      export type InputTuple = [groupId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [groupId: bigint, winner: string, amount: bigint];
      export interface OutputObject {groupId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SafePot extends BaseContract {
    
    connect(runner?: ContractRunner | null): SafePot;
    waitForDeployment(): Promise<this>;

    interface: SafePotInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CREATION_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contribute: TypedContractMethod<
      [groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createGroup: TypedContractMethod<
      [name: string, maxMembers: BigNumberish, contributionAmount: BigNumberish, roundDuration: string, isPrivate: boolean, inviteCode: string, ],
      [void],
      'nonpayable'
    >
    

    
    getGroup: TypedContractMethod<
      [groupId: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, string[], bigint, bigint, bigint, boolean, boolean, string] & {id: bigint, name: string, maxMembers: bigint, contributionAmount: bigint, roundDuration: string, members: string[], currentRound: bigint, potBalance: bigint, currentTurnIndex: bigint, isComplete: boolean, isPrivate: boolean, inviteCode: string }],
      'view'
    >
    

    
    groups: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, bigint, bigint, boolean, boolean, string] & {id: bigint, name: string, maxMembers: bigint, contributionAmount: bigint, roundDuration: string, currentRound: bigint, potBalance: bigint, currentTurnIndex: bigint, isComplete: boolean, isPrivate: boolean, inviteCode: string }],
      'view'
    >
    

    
    hasRugged: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    installmentAmount: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    inviteCodeToGroupId: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    inviterOf: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [string],
      'view'
    >
    

    
    joinGroup: TypedContractMethod<
      [groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    joinPrivateGroup: TypedContractMethod<
      [groupId: BigNumberish, inviteCode: string, ],
      [void],
      'nonpayable'
    >
    

    
    memberContributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    nextGroupId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingInstallments: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    slashInviter: TypedContractMethod<
      [groupId: BigNumberish, memberId: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    slashPublicMember: TypedContractMethod<
      [groupId: BigNumberish, memberId: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CREATION_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createGroup'): TypedContractMethod<
      [name: string, maxMembers: BigNumberish, contributionAmount: BigNumberish, roundDuration: string, isPrivate: boolean, inviteCode: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getGroup'): TypedContractMethod<
      [groupId: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, string[], bigint, bigint, bigint, boolean, boolean, string] & {id: bigint, name: string, maxMembers: bigint, contributionAmount: bigint, roundDuration: string, members: string[], currentRound: bigint, potBalance: bigint, currentTurnIndex: bigint, isComplete: boolean, isPrivate: boolean, inviteCode: string }],
      'view'
    >;
getFunction(nameOrSignature: 'groups'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, bigint, bigint, boolean, boolean, string] & {id: bigint, name: string, maxMembers: bigint, contributionAmount: bigint, roundDuration: string, currentRound: bigint, potBalance: bigint, currentTurnIndex: bigint, isComplete: boolean, isPrivate: boolean, inviteCode: string }],
      'view'
    >;
getFunction(nameOrSignature: 'hasRugged'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'installmentAmount'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inviteCodeToGroupId'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inviterOf'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'joinGroup'): TypedContractMethod<
      [groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinPrivateGroup'): TypedContractMethod<
      [groupId: BigNumberish, inviteCode: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'memberContributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextGroupId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingInstallments'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'slashInviter'): TypedContractMethod<
      [groupId: BigNumberish, memberId: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slashPublicMember'): TypedContractMethod<
      [groupId: BigNumberish, memberId: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ContributionMade'): TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
getEvent(key: 'GroupCreated'): TypedContractEvent<GroupCreatedEvent.InputTuple, GroupCreatedEvent.OutputTuple, GroupCreatedEvent.OutputObject>;
getEvent(key: 'JoinedGroup'): TypedContractEvent<JoinedGroupEvent.InputTuple, JoinedGroupEvent.OutputTuple, JoinedGroupEvent.OutputObject>;
getEvent(key: 'PotDistributed'): TypedContractEvent<PotDistributedEvent.InputTuple, PotDistributedEvent.OutputTuple, PotDistributedEvent.OutputObject>;

    filters: {
      
      'ContributionMade(uint256,address,uint256)': TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
      ContributionMade: TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
    

      'GroupCreated(uint256,string,address)': TypedContractEvent<GroupCreatedEvent.InputTuple, GroupCreatedEvent.OutputTuple, GroupCreatedEvent.OutputObject>;
      GroupCreated: TypedContractEvent<GroupCreatedEvent.InputTuple, GroupCreatedEvent.OutputTuple, GroupCreatedEvent.OutputObject>;
    

      'JoinedGroup(uint256,address)': TypedContractEvent<JoinedGroupEvent.InputTuple, JoinedGroupEvent.OutputTuple, JoinedGroupEvent.OutputObject>;
      JoinedGroup: TypedContractEvent<JoinedGroupEvent.InputTuple, JoinedGroupEvent.OutputTuple, JoinedGroupEvent.OutputObject>;
    

      'PotDistributed(uint256,address,uint256)': TypedContractEvent<PotDistributedEvent.InputTuple, PotDistributedEvent.OutputTuple, PotDistributedEvent.OutputObject>;
      PotDistributed: TypedContractEvent<PotDistributedEvent.InputTuple, PotDistributedEvent.OutputTuple, PotDistributedEvent.OutputObject>;
    
    };
  }